version: '3.2'

services:

  client:
    image: consul:1.0.6
    command: "agent -retry-join server-bootstrap -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"
    depends_on:
      - server-bootstrap
    deploy:
      replicas: 2

  server:
    image: consul:1.0.6
    depends_on:
      - server-bootstrap
    command: "agent -server -retry-join server-bootstrap -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"
    deploy:
      replicas: 2
      
  server-bootstrap:
    image: consul:1.0.6
    ports:
      - "8500:8500"
      # - "8400:8400"
      # - "8600:8600"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"

networks:
  default:
    external:
      name: core-infra
